apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 5173        # Service port
      targetPort: 5173  # Container port
      # nodePort is omitted → k8s will assign a free port automatically
