apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 5173        # Cluster port
      targetPort: 5173  # Pod port
      nodePort: 31007   # NodePort for external access
